### ISSUE TITLE
Cannot edit or delete object in "My Stations" folder

### ISSUE THREAD

**Issue by UC3829** [dersphere/plugin.audio.radio_de#11] opened 2016-03-16 05:19 UTC
```
ERROR: EXCEPTION Thrown (PythonToCppException) : 

-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: <type 'exceptions.ValueError'>
Error Contents: Bad category_type

Traceback (most recent call last):

File "/storage/.kodi/addons/plugin.audio.radio_de/addon.py", line 278, in <module> plugin.run()
File "/storage/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run items = self._dispatch(self.request.path)
File "/storage/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch listitems = view_func(**items)
File "/storage/.kodi/addons/plugin.audio.radio_de/addon.py", line 174, in show_stations_by_category category)
File "/storage/.kodi/addons/plugin.audio.radio_de/resources/lib/api.py", line 91, in get_stations_by_category raise ValueError('Bad category_type')
ValueError: Bad category_type

-->End of Python script error report<--
```

Offending item in **my_stations.json**

`,1457894752.9122369],"Test stream":[{"stream_url":"","is_custom":"1","thumbnail":"","name":"","id":""},`

**Comment by AndreaLombardo** [comment] 2016-04-28 17:42
Hi, I'have similar problem, when creating a custom station, kodi puts two same stations, both playable and working fine. When I try to delete one of they, the remaining station not work and i can't delete it because the "Remove from my stations" is not displayed in the menù. Thanks

**Comment by AndreaLombardo** [comment] 2016-04-28 18:08
Solved manually editing ~/.kodi/userdata/addon_data/plugin.audio.radio_de/.storage/my_stations.json

**Comment by dersphere** [comment] 2017-06-07 09:37
Closing as I could not reproduce. If you still see this error, please reopen with a more detailed description.
Thanks for reporting anyway! :)

**Closed by dersphere** 2017-06-07 09:37 UTC
